name: base_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
dependencies:
  mysql1: ^0.20.0
  shelf: ^1.2.0
  shelf_router: ^1.1.3

  commons_core:
    path: ./packages/commons/commons-core
